name: speaky
description: "Application d'aide aux personnes muettes"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_tts: ^4.2.2
  toastification: ^3.0.2
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/keyboard/




# dart run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#1e6fd9" # Background color for the splash screen
  image: assets/app icon/speaky icon transparent.png
  android_12: 
    image: assets/app icon/speaky icon transparent.png # Path to your loading image

